server:
  port: 9946
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/signIn-system?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
#redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
#mybatis 配置
mybatis:
  type-aliases-package: com.example.SignInsystem.entity
  mapper-locations: classpath:mapper/*.xml